/**
 * @file noop_ai_provider.cpp
 */

#include "noop_ai_provider.hpp"

#include "foundation/error.hpp"
#include "foundation/string.hpp"

namespace scope::ai
{

namespace
{

std::string heuristicFilter(std::string_view naturalLanguageQuery)
{
    const std::string normalized = foundation::toLower(foundation::trim(std::string(naturalLanguageQuery)));

    if (normalized.find("error") != std::string::npos)
    {
        return "level == ERROR";
    }

    if (normalized.find("warn") != std::string::npos)
    {
        return "level == WARN";
    }

    if (normalized.find("info") != std::string::npos)
    {
        return "level == INFO";
    }

    return std::string();
}

} // namespace

std::string NoOpAiProvider::id() const
{
    return kProviderNoOp;
}

foundation::Result<std::string> NoOpAiProvider::translateNlToFilter(std::string_view naturalLanguageQuery) const
{
    const std::string filter = heuristicFilter(naturalLanguageQuery);

    if (filter.empty())
    {
        return foundation::Result<std::string>(foundation::Error(
            foundation::ErrorCode::InvalidArgument,
            "Noop provider could not map natural language query to filter DSL."));
    }

    return foundation::Result<std::string>(filter);
}

foundation::Result<AiSummary> NoOpAiProvider::summarize(const AiInvestigationContext& context) const
{
    AiSummary summary;

    summary.summary = context.sourceSummary.empty() ? "Investigation summary unavailable." : context.sourceSummary;
    summary.reasoning = "Generated by noop provider from investigation metadata.";
    summary.confidence = "low";
    summary.evidence = context.sampleLines;

    if (context.matchCount == 0U)
    {
        summary.suggestedActions.push_back("Broaden filters or verify the log source contains matching events.");
    }
    else
    {
        summary.suggestedActions.push_back("Review cited evidence lines for root-cause patterns.");
    }

    return foundation::Result<AiSummary>(std::move(summary));
}

foundation::Result<std::vector<AiAnomalyHint>> NoOpAiProvider::suggestAnomalies(
    const AiAnalyticsContext& context) const
{
    std::vector<AiAnomalyHint> hints;

    if (context.hasSpike)
    {
        AiAnomalyHint hint;
        hint.severity = "medium";
        hint.message = context.spikeVerdict.empty() ? "Error rate spike detected in timeline trends."
                                                    : context.spikeVerdict;
        hints.push_back(std::move(hint));
    }

    if (context.clusterCount > 0U && !context.topClusterMessage.empty())
    {
        AiAnomalyHint hint;
        hint.severity = "low";
        hint.message = "Repeated error cluster: " + context.topClusterMessage;
        hints.push_back(std::move(hint));
    }

    return foundation::Result<std::vector<AiAnomalyHint>>(std::move(hints));
}

} // namespace scope::ai
